name: plant_disease_detection
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.2
  tflite: ^1.1.0
  meta: ^1.7.0
  url_launcher: ^6.0.17
  path_provider: any
  path: any
  # camera: ^0.9.4+16
  open_file: ^3.2.1
  syncfusion_flutter_pdf: ^19.4.43-beta


  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  geolocator: ^8.2.0




  cupertino_icons: ^1.0.2
  flutter_signin_button: ^2.0.0
  fluttertoast: ^8.0.9
  flutter_offline: ^2.1.0
  animated_text_kit: ^4.2.1
  liquid_swipe: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/
    - assets/plantImages/
  
  fonts:
    - family: Ubuntu-Regular
      fonts:
        - asset: fonts/Ubuntu-Regular.ttf

